### ISSUE TITLE
Error ox_inventory

### ISSUE THREAD

**Issue by Edmondio** [Manason/mana_hunting#4]
![image](https://user-images.githubusercontent.com/83596559/235734780-f6a82606-3104-4b9a-866e-2f1af2ace93b.png)

**Comment by Manason** [comment]
I don't have this issue on current main.

**Comment by Edmondio** [comment]
then I took the last version, I always have the message, it prevents the operation of ox_inventory, after several test, I managed to make it work but not in an optimal way
- I delete in item the list
-I restart ox_inventory
-I start mana_hunting
-I put back the items in the list
-I restart ox_inventory
-I restart mana_hunting

And then the script works
I have the impression that oxinventory can't load and if ox_inventory is not loaded then mana_hunting doesn't load

Sorry for my english I am french

**Comment by Manason** [comment]
Yes, if ox_inventory does not load, mana_hunting will not load, as it depends on ox_inventory. If you fix the reason why ox_inventory isn't loading then the hunting script will work as well.
